packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@scarf/scarf": false
  "@nestjs/core": true
  "@parcel/watcher": true
  "@prisma/client": true
  "@prisma/engines": true
  "@tailwindcss/oxide": true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "vue-demi"
